import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    fetch("/api/news?page=2&perPage=20")
      .then((response) => response.json())
      .then((data) => {
        console.log({ data });
      });
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>Oxfin</div>
      </main>
    </>
  );
}
